"""initial schema

Revision ID: 86ba4e4acf35
Revises: 
Create Date: 2026-09-02 18:57:31.730028

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '86ba4e4acf35'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('crawl_runs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('crawl_id', sa.String(length=32), nullable=False),
    sa.Column('query_json', sa.Text(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('sources_attempted', sa.Integer(), nullable=False),
    sa.Column('sources_succeeded', sa.Integer(), nullable=False),
    sa.Column('sources_failed', sa.Integer(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('crawl_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_crawl_runs_crawl_id'), ['crawl_id'], unique=True)

    op.create_table('products',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('brand', sa.String(length=64), nullable=False),
    sa.Column('model', sa.String(length=128), nullable=False),
    sa.Column('canonical_name', sa.String(length=200), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('brand', 'model', name='uq_products_brand_model')
    )
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_products_brand'), ['brand'], unique=False)
        batch_op.create_index(batch_op.f('ix_products_model'), ['model'], unique=False)

    op.create_table('search_cache',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('query_hash', sa.String(length=64), nullable=False),
    sa.Column('crawl_id', sa.String(length=32), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crawl_id'], ['crawl_runs.crawl_id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search_cache', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_cache_query_hash'), ['query_hash'], unique=True)

    op.create_table('variants',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('product_id', sa.Integer(), nullable=False),
    sa.Column('storage', sa.String(length=32), nullable=True),
    sa.Column('colour', sa.String(length=64), nullable=True),
    sa.Column('variant_key', sa.String(length=256), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('variants', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_variants_variant_key'), ['variant_key'], unique=True)

    op.create_table('listings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('variant_id', sa.Integer(), nullable=False),
    sa.Column('source', sa.String(length=64), nullable=False),
    sa.Column('product_name_raw', sa.String(length=300), nullable=False),
    sa.Column('sku', sa.String(length=128), nullable=True),
    sa.Column('product_url', sa.String(length=600), nullable=True),
    sa.Column('image_url', sa.String(length=600), nullable=True),
    sa.Column('currency', sa.String(length=8), nullable=False),
    sa.Column('mrp', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('selling_price', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('discount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('availability', sa.String(length=32), nullable=True),
    sa.Column('seller', sa.String(length=120), nullable=True),
    sa.Column('rating', sa.Float(), nullable=True),
    sa.Column('review_count', sa.Integer(), nullable=True),
    sa.Column('crawl_id', sa.String(length=32), nullable=False),
    sa.Column('scraped_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['crawl_id'], ['crawl_runs.crawl_id'], ),
    sa.ForeignKeyConstraint(['variant_id'], ['variants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_listings_crawl_id'), ['crawl_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_listings_scraped_at'), ['scraped_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_listings_source'), ['source'], unique=False)
        batch_op.create_index(batch_op.f('ix_listings_variant_id'), ['variant_id'], unique=False)

    op.create_table('offers',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('listing_id', sa.Integer(), nullable=False),
    sa.Column('offer_text', sa.String(length=500), nullable=True),
    sa.Column('offer_type', sa.String(length=32), nullable=True),
    sa.Column('bank', sa.String(length=80), nullable=True),
    sa.Column('offer_discount', sa.Numeric(precision=12, scale=2), nullable=True),
    sa.Column('emi_available', sa.Boolean(), nullable=False),
    sa.Column('emi_tenure', sa.Integer(), nullable=True),
    sa.Column('emi_rate', sa.Float(), nullable=True),
    sa.Column('valid_till_text', sa.String(length=120), nullable=True),
    sa.ForeignKeyConstraint(['listing_id'], ['listings.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_offers_listing_id'), ['listing_id'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('offers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_offers_listing_id'))

    op.drop_table('offers')
    with op.batch_alter_table('listings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_listings_variant_id'))
        batch_op.drop_index(batch_op.f('ix_listings_source'))
        batch_op.drop_index(batch_op.f('ix_listings_scraped_at'))
        batch_op.drop_index(batch_op.f('ix_listings_crawl_id'))

    op.drop_table('listings')
    with op.batch_alter_table('variants', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_variants_variant_key'))

    op.drop_table('variants')
    with op.batch_alter_table('search_cache', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_cache_query_hash'))

    op.drop_table('search_cache')
    with op.batch_alter_table('products', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_products_model'))
        batch_op.drop_index(batch_op.f('ix_products_brand'))

    op.drop_table('products')
    with op.batch_alter_table('crawl_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_crawl_runs_crawl_id'))

    op.drop_table('crawl_runs')
    # ### end Alembic commands ###
